server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/se
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
