server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
#    url: jdbc:postgresql://120.79.200.84:5432/se
    url: jdbc:postgresql://43.139.159.107:5432/se
    username: checker
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # for the bug in Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    database: 0
#    host: 120.79.200.84
    host: 43.139.159.107
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 3000
        min-idle: 2
    port: 6379
    timeout: 5000

sa-token:
  activity-timeout: -1
  is-concurrent: true
  is-log: false
  is-share: true
  timeout: 2592000
  token-name: satoken
  token-style: uuid
